version: '3.9'

services:
  producer-application:
    image: producer
    build: producer
    container_name: producer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
    networks:
      - stream

  consumer-application:
    image: consumer
    build: consumer
    container_name: consumer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
    networks:
      - stream


  rabbitmq:
    image: rabbitmq:3.8.11-management
    container_name: rabbitmq
    mem_limit: 350m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - stream

networks:
  stream:
