spring:
  cloud:
    stream:
      bindings:
        drinkIt-in-0:
          destination: sink
          group: sink
          binder: rabbit

      kafka:
        binder:
          auto-add-partitions: true
          min-partition-count: 4
server:
  port: 0

---
server.port: 80

spring:
  config:
    activate:
      on-profile: docker

  rabbitmq:
    host: rabbitmq
