spring:
  application:
    name: spring-cloud-streams-kotlin
  cloud:
    function:
      definition: uppercase|reverse,uppercase
#      definition: uppercase|reverseWitMessage,uppercase
  rabbitmq:
    host: ${RABBIT_HOST}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    password: ${RABBIT_PASSWORD}
    username: ${RABBIT_USERNAME}
